# DB_HOST environment variable is there already in image, but if we want to override environment variables in run time through ConfigMap 

kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # labels of deployemnt resource
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
  # As we have many pods ,we should give what labels the deployment to match
    matchLabels:
      app: backend
      tier: backend
      project: expense
  # pod template
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: expense
        image: jayakrishna1993/backend:1.0.0
        envFrom:
        - configMapRef:
            name: backend

---

kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:     #labels are used as selectors
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 8080    #service port
    targetPort: 8080   #target container port